Repository pivotal-cf/docs-pks, pull requests merged in 2018-10, with the labels that each got.

#377 Updating language for known issue re: network profiles
  release-notes.html.md.erb
Labels: in progress

#376 Remove the 'completing aws lb page'
  aws-api-load-balancer.html.md.erb
  aws-lb-config.html.md.erb
  installing-pks-aws.html.md.erb
Labels: in progress

#378 manage-users page curl command Header typo
  manage-users.html.md.erb
Labels: scheduled

#389 Adding known issue for 1.2 with NSX-T PI Cert gen when using PKS tile
  release-notes.html.md.erb
Labels: unscheduled

#390 Update wording for Service Network field
  installing-nsx-t.html.md.erb
Labels: in progress

#393 PKS CLI doc update
  cli/index.html.md.erb
Labels: unscheduled

#395 Remove service ls
  nsxt-prepare-env.html.md.erb
Labels: in progress

#399 Pvs nsxt edits
  configuring-pvs.html.md.erb
  installing-nsx-t.html.md.erb
  network-profiles.html.md.erb
  vsphere-persistent-storage.html.md.erb
Labels: in progress

#402 Set an expectation about cluster creation time
  create-cluster.html.md.erb
Labels: in progress

#404 Update release-notes.html.md.erb
  release-notes.html.md.erb
Labels: in progress

#409 Fix formatting for script element
  generate-nsx-pi-cert.html.md.erb
Labels: in progress

#407 121 routable pods
  network-profiles.html.md.erb
Labels: in progress

#411 PV & Proxy fixes
  installing-pks-vsphere.html.md.erb
  vsphere-persistent-storage.html.md.erb
Labels: scheduled

#412 Doc updates
  aws-prepare-env.html.md.erb
  images/resources.png
  installing-pks-aws.html.md.erb
Labels: in progress

#414 Add clarfication and screens for generating wildcard cert for PKS API
  _pks-api.html.md.erb
  images/pks-api-cert-gen.png
  images/pks-api.png
Labels: unscheduled

#416 Add Ops Mgr 2.3.2 known issue to docs
  release-notes.html.md.erb
Labels: scheduled

#417 Fix bugs with Reg NSX CA Cert instructions
  generate-nsx-ca-cert.html.md.erb
Labels: unscheduled

#418 Remove this release note: it was mistakenly reported and verified not…
  release-notes.html.md.erb
Labels: unscheduled

#413 Routable pods
  images/nsxt/routable-pods-01.png
  images/nsxt/routable-pods-02.png
  network-profiles.html.md.erb
  nsxt-prepare-env.html.md.erb
Labels: scheduled

#420 Adding draft of 1.2.1 release notes
  release-notes.html.md.erb
Labels: scheduled

#421 See ODPKS #161269873
  release-notes.html.md.erb
Labels: unscheduled

#422 Edit AWS docs after following Terraform-AWS script
  aws-index.html.md.erb
  aws-om-config.html.md.erb
  aws-prepare-env.html.md.erb
Labels: in progress

#423 PKS 1.2 uses Kubernetes 1.11
  access-dashboard.html.md.erb
Labels: unscheduled

#424 Cidr range 158387175
  images/networking-flannel.png
  installing-pks-aws.html.md.erb
  installing-pks-gcp.html.md.erb
  installing-pks-vsphere.html.md.erb
Labels: unscheduled

#426 Update screenshot showing NSX-T errand selected
  images/nsxt/nsxt-validation-errand-ON.png
  installing-nsx-t.html.md.erb
Labels: in progress
