Repository pivotal-cf/docs-pks, pull requests merged in 2018-09, with the labels that each got.

#327 Adding documentation for using groups
  _uaa.html.md.erb
  manage-users.html.md.erb
Labels: unscheduled

#328 Should make the distinction with PKS tile
  upgrading.html.md.erb
Labels: unscheduled

#330 Update bbr restore for Single Master Cluster
  bbr-restore-cluster.html.md.erb
Labels: unscheduled

#329 Cleanup PKS to PKS Cluster
  bbr-backup-cluster.html.md.erb
Labels: unscheduled

#335 Nikitarathi23 cluster access 159932914
  _uaa.html.md.erb
  manage-users.html.md.erb
Labels: in progress

#326 Add documentation for Naomi's OIDC flow
  _uaa.html.md.erb
  manage-users.html.md.erb
Labels: in progress

#337 Fixes two issues with nsxt cert commands
  generate-certificates.html.md.erb
Labels: in progress

#336 Updates to the NSXT upgrade instructions
  images/upgrade-nsxt-2.png
  images/upgrade-nsxt-3.png
  images/upgrade-nsxt-4.png
  images/upgrade-nsxt-5.png
  images/upgrade-nsxt-6.png
  images/upgrade-nsxt-7.png
  images/upgrade-nsxt-8.png
  images/upgrade-nsxt-9.png
  upgrade-pks-nsxt.html.md.erb
Labels: in progress

#339 Change default settings for persistent and ephemeral disks
  aws-requirements.html.md.erb
  gcp-requirements.html.md.erb
  images/plan1.png
  images/plan2.png
  vsphere-requirements.html.md.erb
Labels: unscheduled

#334 Updates to Bosh config steps and screens for vCenter > NSXT
  images/bosh-director-tile.png
  images/vcenter-config-2.png
  images/vcenter-config-3.png
  images/vcenter-config-4.png
  vsphere-nsxt-om-config.html.md.erb
Labels: in progress

#344 [Updated] Separate OMs
  _pas-and-pks.html.md.erb
Labels: unscheduled

#345 Update disk size 160506482 160506468
  gcp-requirements.html.md.erb
  images/plan1.png
  images/plan2.png
  vsphere-requirements.html.md.erb
Labels: unscheduled

#346 Adding AWS storage class
  volumes.html.md.erb
Labels: unscheduled

#343 Change docs to create a classical load balancer
  aws-api-load-balancer.html.md.erb
  aws-prepare-env.html.md.erb
Labels: in progress

#347 Adds NSX-T 2.2 support for vSphere with NSX-T
  vsphere-nsxt-requirements.html.md.erb
Labels: unscheduled

#348 Adding Maximum number of workers field
  _plans.html.md.erb
Labels: scheduled

#349 Updated release notes for 1.2.
  release-notes.html.md.erb
Labels: unscheduled

#338 Network Profiles documentation
  about-lb.html.md.erb
  cli/index.html.md.erb
  network-profiles.html.md.erb
Labels: in progress

#353 Update release-notes.html.md.erb
  release-notes.html.md.erb
Labels: unscheduled

#357 Update release-notes.html.md.erb
  release-notes.html.md.erb
Labels: unscheduled

#359 Update release-notes.html.md.erb
  release-notes.html.md.erb
Labels: unscheduled

#360 Update aws-lb-config.html.md.erb
  aws-lb-config.html.md.erb
Labels: unscheduled

#362 Update release-notes.html.md.erb
  release-notes.html.md.erb
Labels: unscheduled

#361 Adding new way to add passrole to the user
  aws-prepare-env.html.md.erb
Labels: scheduled

#363 Remove manual logical switch for service network, no longer needed
  nsxt-prepare-env.html.md.erb
Labels: unscheduled

#367 Added final step on configuring LB for GCP
  gcp-cluster-load-balancer.html.md.erb
Labels: unscheduled

#366 Docs for LB in AWS
  aws-cluster-load-balancer.html.md.erb
Labels: unscheduled

#369 Fix indentation
  manage-users.html.md.erb
Labels: unscheduled

#368 PKS 1.2 cli updates
  cli/index.html.md.erb
Labels: scheduled

#370 Update release-notes.html.md.erb
  release-notes.html.md.erb
Labels: unscheduled

#371 Clarify NSX-T LB support in PKS 1.2
  about-lb.html.md.erb
Labels: unscheduled

#372 Change to nsx lb support
  about-lb.html.md.erb
Labels: in progress
