Repository pivotal-cf/docs-pks, pull requests merged in 2018-11, with the labels that each got.

#432 Update release notes and release date for 1.2.1
  release-notes.html.md.erb
Labels: unscheduled

#433 Add note about clusters with more than 200 workers
  _plans.html.md.erb
Labels: unscheduled

#434 Remove restriction on total number of workers
  release-notes.html.md.erb
Labels: unscheduled

#435 Update manage-users.html.md.erb
  manage-users.html.md.erb
Labels: unscheduled

#436 Update manage-users.html.md.erb
  manage-users.html.md.erb
Labels: unscheduled

#430 Added warning to all PKS tile installation sections and RNs
  installing-nsx-t.html.md.erb
  installing-pks-aws.html.md.erb
  installing-pks-gcp.html.md.erb
  installing-pks-vsphere.html.md.erb
  release-notes.html.md.erb
Labels: in progress

#437 Fix for #161649859
  vsphere-om-config.html.md.erb
Labels: scheduled

#438 Fix for #161649859
  vsphere-nsxt-om-config.html.md.erb
  vsphere-om-config.html.md.erb
Labels: unscheduled

#439 Add info on how to get master and worker IAM accounts.
  installing-pks-aws.html.md.erb
Labels: in progress

#441 Update manage-users.html.md.erb
  manage-users.html.md.erb
Labels: scheduled

#443 Update info on no-proxy property with wildcards
  installing-pks-vsphere.html.md.erb
  release-notes.html.md.erb
Labels: in progress

#446 Update aws-om-config.html.md.erb
  aws-om-config.html.md.erb
Labels: unscheduled

#447 Update aws-om-config.html.md.erb
  aws-om-config.html.md.erb
Labels: unscheduled

#448 Remove large option for LB selection--not supported until bare metal …
  network-profiles.html.md.erb
Labels: unscheduled

#442 Pks proxy
  images/pks-proxy-arch.png
  images/pks-proxy-config.png
  installing-nsx-t.html.md.erb
  proxies.html.md.erb
Labels: in progress

#449 Adding topic for installing Istio on PKS with Helm
  helm.html.md.erb
  images/nsxt/istio-on-pks.png
  istio-on-pks.md.html.md.erb
Labels: in progress

#450 Frontend config only allows single port or range
  gcp-api-load-balancer.html.md.erb
Labels: in progress

#445 Azure 161092666
  _azs-networks-azure.html.md.erb
  _plans-azure.html.md.erb
  azs-networks-azure.png
  azure-api-load-balancer.html.md.erb
  azure-cluster-load-balancer.html.md.erb
  azure-index.html.md.erb
  azure-om-config.html.md.erb
  azure-om-deploy.html.md.erb
  azure-prepare-env.html.md.erb
  azure-requirements.html.md.erb
  images/azure-config.png
  images/azure/azs-networks-azure.png
  images/azure/plan1.png
  images/cloud-azure.png
  images/director-tile-azure.png
  images/storage-accounts.png
  index.html.md.erb
  installing-pks-azure.html.md.erb
  installing.html.md.erb
Labels: scheduled

#452 Update max worker statement
  vm-sizing.html.md.erb
Labels: unscheduled

#453 Updates from dev
  istio-on-pks.html.md.erb
Labels: in progress

#454 123 ncp proxy
  images/pks-proxy-arch.png
  images/pks-proxy-config.png
  proxies.html.md.erb
Labels: scheduled

#455 123 large lb
  network-profiles.html.md.erb
  nsxt-topologies.html.md.erb
Labels: scheduled
