Repository pivotal-cf/docs-pks, pull requests merged in 2018-06, with the labels that each got.

#219 Update Component Versions and Features in the PKS 1.1 Release Notes
  installing-nsx-t.html.md.erb
  release-notes.html.md.erb
  vsphere-requirements.html.md.erb
Labels: unscheduled

#220 Remove vSphere worker credentials
  installing-pks.html.md.erb
  release-notes.html.md.erb
  vsphere-prepare-env.html.md.erb
Labels: in progress

#221 Update docs to note ABAC removal in 1.1
  installing-pks.html.md.erb
  release-notes.html.md.erb
Labels: scheduled

#222 fix a few things
  installing-pks.html.md.erb
Labels: scheduled

#224 Add CLI timeout issue into Known Issues
  release-notes.html.md.erb
Labels: in progress

#225 Remove NSX-T 2.2 and vSphere 6.7 from PKS 1.1 supported configurations
  release-notes.html.md.erb
  vsphere-requirements.html.md.erb
Labels: unscheduled

#226 Update CFCR and golang versions
  release-notes.html.md.erb
Labels: in progress

#227 Changed location of UAA admin creds for PKS 1.1.0
  configure-api.html.md.erb
Labels: unscheduled

#228 Cloud provider for GCP updated to ask for service account name
  gcp-prepare-env.html.md.erb
  installing-pks.html.md.erb
Labels: scheduled

#229 Feature/vm size
  release-notes.html.md.erb
Labels: in progress

#231 Update the PKS API Load Balancer documentation to be more clear
  gcp-api-load-balancer.html.md.erb
  installing-pks.html.md.erb
Labels: in progress

#232 Update vRLi, Wavefront, and Networking tab in PKS tile.
  installing-nsx-t.html.md.erb
  installing-pks.html.md.erb
Labels: in progress

#233 Revert " Update vRLi, Wavefront, and Networking tab in PKS tile."
  installing-nsx-t.html.md.erb
  installing-pks.html.md.erb
Labels: unscheduled

#234 Copy edits on cross-references.
  installing-nsx-t.html.md.erb
  installing-pks-cli.html.md.erb
  installing-pks.html.md.erb
  release-notes.html.md.erb
  troubleshoot-issues.html.md.erb
  vsphere-om-config.html.md.erb
  vsphere-prepare-env.html.md.erb
Labels: scheduled

#237 Remove outdated information about downloading json for gcp accounts
  gcp-prepare-env.html.md.erb
Labels: in progress

#235 Rename GCP service account to ID
  installing-pks.html.md.erb
Labels: in progress

#240 Better LDAP DN example for Administrators Group
  manage-users.html.md.erb
Labels: scheduled

#244 Change `pane` to `plane`
  manage-users.html.md.erb
Labels: unscheduled

#242 Simplify accessing the dashboard instructions.
  access-dashboard.html.md.erb
Labels: in progress

#243 Adding additional minimum worker nodes for multi az
  installing-pks.html.md.erb
Labels: in progress

#248 Added known issue on upgrading #158632463
  release-notes.html.md.erb
Labels: in progress

#249 clarifies the location of UAA for pks-cli
  manage-users.html.md.erb
Labels: scheduled

#251 update stemcell, kubernetes cli and known issues
  release-notes.html.md.erb
Labels: in progress

#252 Final PKS 1.1.0 doc updates.
  images/vsphere/nsxt-edge-ha.png
  images/vsphere/nsxt-topology-nat.png
  images/vsphere/nsxt-topology-no-nat-logical-switch.png
  images/vsphere/nsxt-topology-no-nat-virtual-switch.png
  installing-nsx-t.html.md.erb
  release-notes.html.md.erb
  upgrade-pks.html.md.erb
Labels: unscheduled

#253 Add vSphere upgrade instructions that were removed by mistake.
  about-lb.html.md.erb
  gcp-om-config.html.md.erb
  pks-api-auth.html.md.erb
  release-notes.html.md.erb
  upgrade-pks.html.md.erb
Labels: in progress

#255 Critical doc updates for PKS 1.1.0 GA post-release.
  installing-nsx-t.html.md.erb
  release-notes.html.md.erb
Labels: unscheduled
