Repository pivotal-cf/docs-pks, pull requests merged in 2018-04, with the labels that each got.

#178 Add events that interrupt service page
  interruptions.html.md.erb
Labels: in progress

#181 Add new firewall ports topic and xref from NSX-T instructions.
  installing-nsx-t.html.md.erb
  ports-protocols-nsx-t.html.md.erb
Labels: scheduled

#182 Update release note for NSX-T password requirement.
  release-notes.html.md.erb
Labels: scheduled

#184 Make docker_ctl executable, so fix will work
  1.0.2/stemcell/docker_ctl_update.sh
Labels: in progress

#185 Update documentation for AWS
  aws-om-deploy.html.md.erb
  aws-prepare-env.html.md.erb
  aws-requirements.html.md.erb
  aws.html.md.erb
  index.html.md.erb
  installing-pks-aws.html.md.erb
Labels: in progress

#186 Style copy edits for cross-references and one fix to PKS link.
  access-dashboard.html.md.erb
  configure-tiller-helm.html.md.erb
  deploy-workloads.html.md.erb
  diagnostic-tools.html.md.erb
  gcp-om-config.html.md.erb
  gcp-om-deploy.html.md.erb
  gcp-prepare-env.html.md.erb
  helm.html.md.erb
  installing-nsx-t.html.md.erb
  installing-pks-gcp.html.md.erb
  installing-pks-vsphere.html.md.erb
  interruptions.html.md.erb
  troubleshoot-issues.html.md.erb
  upgrade-pipeline.html.md.erb
  upgrade-pks.html.md.erb
  using.html.md.erb
  volumes.html.md.erb
  vsphere-om-config.html.md.erb
Labels: in progress

#192 Copy edits for stylistic consistency.
  images/nsx-t-edge-ha.png
  installing-nsx-t.html.md.erb
  installing-pks-cli.html.md.erb
  installing-pks-vsphere.html.md.erb
  upgrade-pipeline.html.md.erb
  upgrade-pks.html.md.erb
  vsphere-om-config.html.md.erb
  vsphere-om-deploy.html.md.erb
  vsphere-prepare-env.html.md.erb
  vsphere-requirements.html.md.erb
Labels: in progress

#195 Add documentation for creating LB for PKS API on AWS
  installing-pks-aws.html.md.erb
Labels: in progress

#194 Update pointer to login topic.
  _login-pks-api.html.md.erb
Labels: scheduled

#197 Revert "Update pointer to login topic."
  _login-pks-api.html.md.erb
Labels: unscheduled

#196 AWS specific steps to setup a load balancer on the workloads
  deploy-workloads.html.md.erb
Labels: in progress
