Repository pivotal-cf/docs-pks, pull requests merged in 2018-07, with the labels that each got.

#260 recommendation for shared datastore
  installing-pks.html.md.erb
Labels: scheduled

#263 Completed release notes for v1.1.0
  release-notes.html.md.erb
Labels: scheduled

#268 Add note for what cidrs to avoid for services network
  gcp-om-config.html.md.erb
  vsphere-om-config.html.md.erb
Labels: in progress

#270 Update NSX docs to also note k8s services reserved cidr
  installing-nsx-t.html.md.erb
Labels: in progress

#271 Note that only `user@domain` is supported for vSphere master creds
  installing-pks.html.md.erb
Labels: in progress

#272 Note that only `user@domain` is supported for vSphere master and worker
  installing-pks.html.md.erb
Labels: in progress

#273 Add documentation about the PKS_HOME env var
  installing-pks-cli.html.md.erb
Labels: in progress

#275 Addresses PKS-896: doc ex for NSX Mgr Cert must specify the SAN
  installing-nsx-t.html.md.erb
Labels: in progress

#261 Create new page with recommendations of VM sizing
  concepts.html.md.erb
  installing-pks.html.md.erb
  vm-sizing.html.md.erb
Labels: in progress

#276 Added data for capacity planning of ephemeral VMs
  vsphere-requirements.html.md.erb
Labels: scheduled

#278 update for 1.1.1 release notes
  release-notes.html.md.erb
Labels: unscheduled

#279 Updating Nodes IP Block size recommendation for PKS with NSX-T installs
  installing-nsx-t.html.md.erb
Labels: in progress

#283 Address issue #280
  vsphere-om-deploy.html.md.erb
Labels: in progress

#282 Addresses Issue 281
  upgrade-pks.html.md.erb
Labels: scheduled

#284 Add docs for getting OIDC-enabled kubeconfig
  cluster-credentials.html.md.erb
  images/oidc1.png
  installing-pks.html.md.erb
  troubleshoot-issues.html.md.erb
Labels: scheduled
