Repository pivotal-cf/docs-pks, pull requests merged in 2018-12, with the labels that each got.

#456 Addresses the 'Director Hostname #293' issue
  vsphere-nsxt-om-config.html.md.erb
  vsphere-om-config.html.md.erb
Labels: in progress

#457 Adding BOSH Director VM to requirements for all IaaS's
  aws-requirements.html.md.erb
  gcp-requirements.html.md.erb
  vsphere-nsxt-requirements.html.md.erb
  vsphere-requirements.html.md.erb
Labels: scheduled

#459 Adding Pods Subnet Prefix for 1.2.3
  network-profiles.html.md.erb
Labels: unscheduled

#461 Multi t0 updates
  images/nsxt/mt0/bgp-04.png
  images/nsxt/mt0/bgp-05.png
  images/nsxt/mt0/ip-set-08.png
  images/nsxt/mt0/snat-yes-nat2.png
  network-profiles-define.html.md.erb
  nsxt-multi-t0.html.md.erb
Labels: unscheduled

#462 Mt0 updates
  about-lb.html.md.erb
  images/nsxt/mt0/uplink-interfaces-shared.png
  images/nsxt/mt0/uplink-interfaces-tenant.png
  network-profiles-define.html.md.erb
  nsxt-multi-t0.html.md.erb
Labels: unscheduled

#463 Mt0 updates more
  images/nsxt/mt0/ip-prefix-01.png
  images/nsxt/mt0/ip-prefix-02.png
  images/nsxt/mt0/ip-prefix-03.png
  images/nsxt/mt0/no-snat-01.png
  images/nsxt/mt0/no-snat-02.png
  network-profiles-define.html.md.erb
  nsxt-multi-t0.html.md.erb
  vsphere-nsxt-index.html.md.erb
Labels: unscheduled

#464 Fixed type: LoadBalancer
  ports-protocols-nsx-t.html.md.erb
Labels: unscheduled

#465 Update release-notes.html.md.erb
  release-notes.html.md.erb
Labels: unscheduled

#467 Porting 1.2.4 nsxt features from master to 1.2.4 branch, update relea…
  images/nsxt/mt0/bgp-01.png
  images/nsxt/mt0/bgp-02.png
  images/nsxt/mt0/bgp-03.png
  images/nsxt/mt0/bgp-04.png
  images/nsxt/mt0/bgp-05.png
  images/nsxt/mt0/firewall-01.png
  images/nsxt/mt0/firewall-02.png
  images/nsxt/mt0/firewall-03.png
  images/nsxt/mt0/firewall-04.png
  images/nsxt/mt0/ip-prefix-01.png
  images/nsxt/mt0/ip-prefix-02.png
  images/nsxt/mt0/ip-prefix-03.png
  images/nsxt/mt0/ip-set-01.png
  images/nsxt/mt0/ip-set-02.png
  images/nsxt/mt0/ip-set-03.png
  images/nsxt/mt0/ip-set-04.png
  images/nsxt/mt0/ip-set-05.png
  images/nsxt/mt0/ip-set-06.png
  images/nsxt/mt0/ip-set-07.png
  images/nsxt/mt0/ip-set-08.png
  images/nsxt/mt0/mt0-01.png
  images/nsxt/mt0/mt0-02.png
  images/nsxt/mt0/no-snat-01.png
  images/nsxt/mt0/no-snat-02.png
  images/nsxt/mt0/nsxt-inter-t0-vlan-01.png
  images/nsxt/mt0/nsxt-inter-t0-vlan-02.png
  images/nsxt/mt0/nsxt-static-routes-01.png
  images/nsxt/mt0/nsxt-static-routes-02.png
  images/nsxt/mt0/snat-01.png
  images/nsxt/mt0/snat-no-nat.png
  images/nsxt/mt0/snat-yes-nat.png
  images/nsxt/mt0/snat-yes-nat2.png
  images/nsxt/mt0/uplink-interfaces-shared.png
  images/nsxt/mt0/uplink-interfaces-tenant.png
  installing-nsx-t.html.md.erb
  network-profiles-define.html.md.erb
  nsxt-multi-t0.html.md.erb
  proxies.html.md.erb
  release-notes.html.md.erb
  vsphere-nsxt-index.html.md.erb
Labels: unscheduled

#468 Update release-notes.html.md.erb
  release-notes.html.md.erb
Labels: unscheduled

#473 Update release-notes.html.md.erb
  release-notes.html.md.erb
Labels: unscheduled

#466 Proxy updates
  proxies.html.md.erb
Labels: in progress

#470 Feedback from GB
  images/nsxt/mt0/Tier-0-HA.png
  images/nsxt/mt0/bgp-01.png
  nsxt-multi-t0.html.md.erb
Labels: in progress

#472 Adding new version of using net profiles
  network-profiles.html.md.erb
Labels: in progress

#474 124 formatting
  nsxt-multi-t0.html.md.erb
  proxies.html.md.erb
Labels: unscheduled

#475 Updates to 124 RNs
  release-notes.html.md.erb
Labels: unscheduled

#471 Updates from 124 source
  images/nsxt/mt0/Tier-0-HA.png
  images/nsxt/mt0/bgp-01.png
  nsxt-multi-t0.html.md.erb
  proxies.html.md.erb
Labels: in progress

#476 Update network profiles params
  network-profiles-define.html.md.erb
Labels: in progress

#478 Update bbr-backup-cluster.html.md.erb
  bbr-backup-cluster.html.md.erb
Labels: unscheduled

#481 Update bbr-restore-cluster.html.md.erb
  bbr-restore-cluster.html.md.erb
Labels: in progress

#479 Adding failed cluster deletion steps and known issue for 1.2
  delete-cluster.html.md.erb
  release-notes.html.md.erb
Labels: in progress

#486 Add docker v to 1.2 rns
  release-notes.html.md.erb
Labels: delivered

#485 Add docker version to RNs for 1.3
  release-notes.html.md.erb
Labels: in progress

#487 Fixes for #483
  images/nsxt/non-routable-pods.png
  images/nsxt/routable-pods.png
Labels: scheduled

#488 Adding Multi-Foundational PKS
  images/nsxt/multi-pks/multi-pks-01.png
  images/nsxt/multi-pks/multi-pks-02.png
  images/nsxt/multi-pks/multi-pks-03.png
  images/nsxt/multi-pks/multi-pks.png
  nsxt-multi-pks.html.md.erb
  vsphere-nsxt-index.html.md.erb
Labels: unscheduled

#489 Update documentation about az on azure
  _plans.html.md.erb
Labels: unscheduled

#494 Updates to stemcell version and known BOSH issue PKS-1058
  release-notes.html.md.erb
Labels: unscheduled

#492 Add PKS and Harbor hostnames to No Proxy -- from feedback
  proxies.html.md.erb
Labels: unscheduled

#491 Fix vSAN w/ shared datastore case + NFS language
  vsphere-persistent-storage.html.md.erb
Labels: unscheduled

#495 Update release-notes.html.md.erb
  release-notes.html.md.erb
Labels: unscheduled

#490 Updates from feedback
  nsxt-multi-pks.html.md.erb
Labels: scheduled

#496 Updating 1.2 RNs with known issue
  release-notes.html.md.erb
Labels: unscheduled

#493 Azure/msi 161311236
  azure-managed-identities.html.md.erb
  images/cloud-azure.png
  installing-pks-azure.html.md.erb
Labels: in progress

#497 Update 1.2.5 Release Notes in 1.2.5 Branch
  release-notes.html.md.erb
Labels: unscheduled
