Repository pivotal-cf/docs-pks, pull requests merged in 2018-08, with the labels that each got.

#299 Link directly to Wavefront PKS Documentation
  installing-pks.html.md.erb
Labels: unscheduled

#300 PKS 1.1 does not support vSphere 6.5 U2, removing
  vsphere-requirements.html.md.erb
Labels: unscheduled

#298 Adding to RNs compatible versions for NSX-T and NCP
  release-notes.html.md.erb
Labels: scheduled

#303 Troubleshooting step for PKS with NSXT upgrade failure
  troubleshoot-issues.html.md.erb
Labels: in progress

#319 Docs pks issue 311 and 313
  aws-prepare-env.html.md.erb
Labels: unscheduled

#318 Story 160073206: pivotal-cf/docs-pks #310: Invalid JSON in Create the…
  aws-prepare-env.html.md.erb
Labels: unscheduled

#308 Adding new topic for PKS with NSX-T Upgrade
  _plans.html.md.erb
  images/upgrade-nsxt.png
  upgrade-pks-nsxt.html.md.erb
Labels: in progress

#321 Revert "Revert "Adding new topic for PKS with NSX-T Upgrade""
  _plans.html.md.erb
  images/upgrade-nsxt.png
  upgrade-pks-nsxt.html.md.erb
Labels: unscheduled

#322 Revert "Revert "Revert "Adding new topic for PKS with NSX-T Upgrade"""
  _plans.html.md.erb
  images/upgrade-nsxt.png
  upgrade-pks-nsxt.html.md.erb
Labels: unscheduled

#324 Adding Known Issues to 115 RNs
  release-notes.html.md.erb
Labels: in progress
