Repository pivotal-cf/docs-pks, pull requests merged in 2019-02, with the labels that each got.

#539 Final updates from feedback
  volumes.html.md.erb
  vsphere-persistent-storage.html.md.erb
Labels: in progress

#541 Fix anchor tag name
  volumes.html.md.erb
Labels: scheduled

#542 Adding RNs for 1.2.7, 1.2.8, 1.2.9 with placeholder for KB
  release-notes.html.md.erb
Labels: in progress

#543 Adding RNs for 1.3.1 and 1.3.2 with placeholders for KB
  release-notes.html.md.erb
Labels: in progress

#544 Known Issue 1.3.0: Cloud Provider Credentials
  release-notes.html.md.erb
Labels: in progress

#546 1.3.1 Release Notes: Added data on cert changes and re-adding CA in …
  release-notes.html.md.erb
Labels: unscheduled

#545 1.2.7 1.2.8 rn
  release-notes.html.md.erb
Labels: unscheduled

#547 1.3 Release Notes Update
  release-notes.html.md.erb
Labels: unscheduled

#548 Update note with new expected behavior
  generate-nsx-ca-cert.html.md.erb
  installing-nsx-t.html.md.erb
Labels: in progress

#550 Fix quote style and first sentence
  azure-om-config.html.md.erb
Labels: unscheduled

#551 Update mt0
  nsxt-multi-t0.html.md.erb
Labels: scheduled

#553 Update Harbor support for Azure
  index.html.md.erb
Labels: scheduled

#555 Adding warning about special chars in cluster name
  create-cluster.html.md.erb
Labels: unscheduled

#557 Fix pod_routable example
  network-profiles-define.html.md.erb
Labels: scheduled

#558 Fix pod_routable type
  network-profiles-define.html.md.erb
Labels: scheduled

#559 Fixing upgrade path to 1.2.7
  release-notes.html.md.erb
Labels: unscheduled

#560 Adding reference to OM API for worker VM customizations
  _plans.html.md.erb
  vm-sizing.html.md.erb
Labels: in progress

#561 Fixing links
  upgrade-pks-nsxt.html.md.erb
Labels: in progress

#562 Incorrect section title in Installing PKS on vSphere with NSX-T
  installing-nsx-t.html.md.erb
Labels: unscheduled

#564 Update number of worker nodes screenshot, remove max
  _plans.html.md.erb
  images/plan2b.png
Labels: in progress

#566 1.3.3 Release notes
  release-notes.html.md.erb
Labels: in progress

#567 1.2.10 Release notes
  release-notes.html.md.erb
Labels: unscheduled

#568 Update K8s version
  release-notes.html.md.erb
Labels: unscheduled

#570 Updating for master node customization
  _plans.html.md.erb
  vm-sizing.html.md.erb
Labels: unscheduled

#569 Network profiles nodes_dns feature
  network-profiles-define.html.md.erb
Labels: unscheduled

#563 Add more details [#164025102]
  nsxt-multi-t0.html.md.erb
Labels: in progress

#571 Add PKS mgmt plane node to reserved IPs list
  nsxt-prepare-env.html.md.erb
Labels: in progress

#572 Removing mention of max worker nodes per PM
  _plans.html.md.erb
Labels: in progress

#574 Added documentation for kubelet customization on the plans page.
  _plans.html.md.erb
Labels: in progress
