Repository pivotal-cf/docs-pks, pull requests merged in 2019-04, with the labels that each got.

#594 Adding support for up to 5 master nodes per Plan
  _plans.html.md.erb
  images/plan1.png
Labels: in progress

#589 Startup shutdown procedure
  images/nsxt/shutdown/maint-mode.png
  images/nsxt/shutdown/shutdown-bosh.png
  images/nsxt/shutdown/shutdown-harbor.png
  images/nsxt/shutdown/shutdown-idrac.png
  images/nsxt/shutdown/shutdown-k8s-nodes.png
  images/nsxt/shutdown/shutdown-nsxt.png
  images/nsxt/shutdown/shutdown-om.png
  images/nsxt/shutdown/shutdown-pks.png
  images/nsxt/shutdown/shutdown-vc.png
  shutdown-startup-procedure.html.md.erb
Labels: in progress

#596 136 nsxt24 upgrade
  images/nsxt/nsx-upgrade/nsx_24_upgrade-00.png
  images/nsxt/nsx-upgrade/nsx_24_upgrade-01.png
  images/nsxt/nsx-upgrade/nsx_24_upgrade-02.png
  images/nsxt/nsx-upgrade/nsx_24_upgrade-03.png
  images/nsxt/nsx-upgrade/nsx_24_upgrade-04.png
  images/nsxt/nsx-upgrade/nsx_24_upgrade-05.png
  images/nsxt/nsx-upgrade/nsx_24_upgrade-06.png
  images/nsxt/nsx-upgrade/nsx_24_upgrade-07.png
  images/nsxt/nsx-upgrade/nsx_24_upgrade-08.png
  images/nsxt/nsx-upgrade/nsx_24_upgrade-09.png
  images/nsxt/nsx-upgrade/nsx_24_upgrade-10.png
  upgrade-pks-nsxt-24.html.md.erb
  upgrading.html.md.erb
Labels: in progress

#595 Adding documentation for update-cluster --network-profile
  network-profiles-define.html.md.erb
  network-profiles.html.md.erb
Labels: in progress

#599 Removing version info from doc
  upgrade-pks-nsxt.html.md.erb
Labels: scheduled

#602 Updates to URLs
  upgrade-pks-nsxt-24.html.md.erb
Labels: scheduled

#600 Add snippets for increasing persistent disk size
  _increase_persistent_disk.html.md.erb
  aws-requirements.html.md.erb
  azure-requirements.html.md.erb
  gcp-requirements.html.md.erb
  troubleshoot-issues.html.md.erb
  vsphere-nsxt-rpd-mpd.html.md.erb
  vsphere-requirements.html.md.erb
Labels: scheduled

#603 136 rns
  release-notes.html.md.erb
Labels: unscheduled

#604 Updates
  _vsphere_versions.html.md.erb
  release-notes.html.md.erb
Labels: unscheduled

#605 Crucial fix
  upgrade-pks-nsxt-24.html.md.erb
Labels: in progress

#607 Azure rg known issue
  release-notes.html.md.erb
Labels: in progress

#606 Add location of ca cert to documentation
  manage-users.html.md.erb
Labels: in progress

#608 Adding nodes_dns to net prof params list, and other clean up based on…
  network-profiles-define.html.md.erb
Labels: in progress

#609 Fix statement to make it more accurate
  generate-nsx-ca-cert.html.md.erb
Labels: scheduled

#610 Adding how to get the nsx-t 2.4.0.1 hot-patch
  release-notes.html.md.erb
  upgrade-pks-nsxt-24.html.md.erb
Labels: scheduled

#597 Adding vShphere host groups content
  images/nsxt/bosh/config-bosh-29-host-group.png
  images/vsphere/vSphere-host-group.png
  vsphere-host-group.html.md.erb
  vsphere-nsxt-om-config.html.md.erb
Labels: in progress

#601 Pod security policies 1.4
  admission-plugins.html.md.erb
  deny-escalating-execution.html.md.erb
  images/admission-plugins.png
  images/psp-default.png
  images/psp-denyescexe.png
  images/psp-enable.png
  images/psp-roles.png
  images/psp-seccontextdeny.png
  images/psps.vsdx
  pod-security-policy.html.md.erb
  security-context-deny.html.md.erb
Labels: delivered

#611 Vertical scaling k8s vms
  images/upgrade-all-clusters-errand.png
  scale-clusters.html.md.erb
Labels: in progress

#612 Corrected Control Plugin name
  admission-plugins.html.md.erb
Labels: in progress

#613 Fixing ref paths so the topics render correctly in VMW MD2HTML tool
  aws-cluster-load-balancer.html.md.erb
  create-cluster.html.md.erb
  deploy-workloads.html.md.erb
Labels: unscheduled

#614 Updates to PSP docs with R1 feedback from MG
  images/psp-default.png
  images/psps.vsdx
  pod-security-policy.html.md.erb
Labels: unscheduled

#615 Updates to host groups from PM feedback
  vsphere-host-group.html.md.erb
Labels: in progress

#616 Updates to 5 master nodes based on PM feedback
  _plans.html.md.erb
Labels: in progress

#617 Updates to newtork-profiles from feedback
  network-profiles-define.html.md.erb
Labels: unscheduled

#618 Updates to PSP from feedback
  pod-security-policy.html.md.erb
Labels: unscheduled

#619 140 upgrades
  checklist.html.md.erb
  images/nsxt/nsx-upgrade/nsx_24_upgrade-00.png
  images/nsxt/nsx-upgrade/nsx_24_upgrade-01.png
  images/nsxt/nsx-upgrade/nsx_24_upgrade-02.png
  images/nsxt/nsx-upgrade/nsx_24_upgrade-03.png
  images/nsxt/nsx-upgrade/nsx_24_upgrade-04.png
  images/nsxt/nsx-upgrade/nsx_24_upgrade-05.png
  images/nsxt/nsx-upgrade/nsx_24_upgrade-06.png
  images/nsxt/nsx-upgrade/nsx_24_upgrade-07.png
  images/nsxt/nsx-upgrade/nsx_24_upgrade-08.png
  images/nsxt/nsx-upgrade/nsx_24_upgrade-09.png
  images/nsxt/nsx-upgrade/nsx_24_upgrade-10.png
  upgrade-pks-nsxt.html.md.erb
  upgrade-pks.html.md.erb
Labels: unscheduled

#620 Misc feedback
  _plans.html.md.erb
  admission-plugins.html.md.erb
  deny-escalating-execution.html.md.erb
  security-context-deny.html.md.erb
  upgrade-pks-nsxt.html.md.erb
  vsphere-host-group.html.md.erb
Labels: unscheduled

#621 Updates to HostGroups from PM feedback on use cases
  vsphere-host-group.html.md.erb
Labels: unscheduled

#622 Psp updates
  checklist.html.md.erb
  pod-security-policy.html.md.erb
Labels: unscheduled

#623 Stemcell version update
  release-notes.html.md.erb
Labels: unscheduled

#624 Updates to PSPs from feedback
  admission-plugins.html.md.erb
  deny-escalating-execution.html.md.erb
  images/psp-enable.png
  pod-security-policy.html.md.erb
  security-context-deny.html.md.erb
Labels: unscheduled

#625 Pks upgrade
  generate-nsx-ca-cert.html.md.erb
  upgrade-pks-nsxt.html.md.erb
Labels: unscheduled

#626 Adding content to 1.4 RNs
  release-notes.html.md.erb
Labels: unscheduled

#627 Important fixes to the 1.3 docs
  release-notes.html.md.erb
  upgrade-pks-nsxt-24.html.md.erb
Labels: unscheduled

#628 Nsxt 2.4 installation
  generate-nsx-ca-cert-24.html.md.erb
  generate-nsx-ca-cert.html.md.erb
  nsxt-deploy-24.html.md.erb
  nsxt-deploy.html.md.erb
Labels: unscheduled

#629 Update admission plugin
  admission-plugins.html.md.erb
  checklist.html.md.erb
  deny-escalating-execution.html.md.erb
  pod-security-policy.html.md.erb
Labels: unscheduled

#630 Updates to pks install with nsxt 2.4
  images/nsxt/nsxt-24-ui.png
  nsxt-deploy-24.html.md.erb
Labels: unscheduled

#631 Updates
  nsxt-deploy-24.html.md.erb
  vsphere-nsxt-index.html.md.erb
Labels: unscheduled

#632 Adding fresh install docs for NSXT-2.4
  images/nsxt/nsxt-24-ui.png
  nsxt-deploy-24.html.md.erb
  vsphere-nsxt-index.html.md.erb
Labels: unscheduled

#633 Cli docs
  cli/index.html.md.erb
Labels: in progress

#634 Disable admission plugins
  admission-plugins-disable.html.md.erb
  admission-plugins.html.md.erb
  images/pks-guid.png
  managing.html.md.erb
  pod-security-policy.html.md.erb
Labels: unscheduled

#635 Revert "Adding fresh install docs for NSXT-2.4"
  images/nsxt/nsxt-24-ui.png
  nsxt-deploy-24.html.md.erb
  vsphere-nsxt-index.html.md.erb
Labels: unscheduled

#636 Adding fresh install docs for nsxt 2.4
  generate-nsx-ca-cert-24.html.md.erb
  images/nsxt/nsxt-24-ui.png
  nsxt-deploy-24.html.md.erb
  vsphere-nsxt-index.html.md.erb
Labels: unscheduled

#637 Revert "Revert "Adding fresh install docs for NSXT-2.4""
  vsphere-nsxt-index.html.md.erb
Labels: unscheduled

#638 Feedback on get-kubeconfig for 1.4
  manage-users.html.md.erb
Labels: unscheduled

#639 Changing password
  images/vsphere/pw-change-bosh-nsx.png
  images/vsphere/pw-change-bosh-vc.png
  images/vsphere/pw-change-pks-vc.png
  managing.html.md.erb
  password-management.html.md.erb
Labels: unscheduled

#640 Explanation for step in HA VIP NSX Edge
  nsxt-deploy.html.md.erb
Labels: unscheduled

#642 Fix invalid paths so we can build the docs
  aws-cluster-load-balancer.html.md.erb
  create-cluster.html.md.erb
Labels: unscheduled

#643 Fixing paths for deployment to docs.vmware.com
  aws-cluster-load-balancer.html.md.erb
  create-cluster.html.md.erb
Labels: unscheduled

#644 Fixing Quota commands to allow copy&paste
  _create-auth-token-var.html.md.erb
  resource-usage.html.md.erb
Labels: unscheduled

#645 Fix formatting
  pod-security-policy.html.md.erb
Labels: unscheduled
