Repository pivotal-cf/docs-pks, pull requests merged in 2019-01, with the labels that each got.

#498 Update warning on 2 topologies
  vsphere-persistent-storage.html.md.erb
Labels: unscheduled

#500 PKS 1.2.6 Release Notes
  release-notes.html.md.erb
Labels: unscheduled

#501 Updates to 1.2.5 and 1.2.6 RNs
  release-notes.html.md.erb
Labels: unscheduled

#502 Cli docs - update to 1.3
  cli/index.html.md.erb
Labels: unscheduled

#503 Removing Istio topic per TPM team request
  istio-on-pks.html.md.erb
Labels: scheduled

#506 Release Notes Update for 1.3. MG & RJ
  release-notes.html.md.erb
Labels: unscheduled

#480 Address Issue #295
  images/vsphere/om-deploy-01.png
  images/vsphere/om-deploy-02.png
  images/vsphere/om-deploy-03.png
  images/vsphere/om-deploy-04.png
  images/vsphere/om-deploy-05.png
  images/vsphere/om-deploy-06.png
  images/vsphere/om-deploy-07.png
  images/vsphere/om-deploy-08.png
  images/vsphere/om-deploy-09.png
  images/vsphere/om-deploy-10.png
  images/vsphere/om-deploy-11.png
  images/vsphere/om-deploy-12.png
  images/vsphere/om-deploy-13.png
  images/vsphere/om-deploy-14.png
  images/vsphere/om-deploy-15.png
  images/vsphere/om-deploy-16.png
  images/vsphere/om-deploy-17.png
  images/vsphere/om-deploy-18.png
  images/vsphere/om-deploy-19.png
  vsphere-om-config.html.md.erb
  vsphere-om-deploy.html.md.erb
Labels: in progress

#509 Updated release notes:
  release-notes.html.md.erb
Labels: unscheduled

#508 Issue 507: making the 2 changes
  azure-managed-identities.html.md.erb
Labels: unscheduled

#510 Updates to formatting and nsx-t load balancer support
  nsxt-deploy.html.md.erb
  nsxt-prepare-env.html.md.erb
Labels: in progress

#511 Updates to supported NSX-T versions
  nsxt-multi-t0.html.md.erb
  release-notes.html.md.erb
  vsphere-nsxt-requirements.html.md.erb
Labels: scheduled

#512 Point to release notes for NSX-T version info; add clarification stat…
  release-notes.html.md.erb
  vsphere-nsxt-requirements.html.md.erb
Labels: scheduled

#513 Story 163135365
  _bosh-ssh.html.md.erb
  diagnostic-tools.html.md.erb
  manage-deployments-bosh.html.md.erb
Labels: unscheduled

#516 Adding other network profile features rolled up in 1.3
  release-notes.html.md.erb
Labels: unscheduled

#517 Vsphere storage updates
  images/vsphere/vsphere-pv-a1-vsan.png
  images/vsphere/vsphere-pv-a2-vmfs.png
  vsphere-persistent-storage.html.md.erb
Labels: in progress

#519 public ip vm_extensions as ignored for azure
  installing-pks-azure.html.md.erb
Labels: unscheduled

#521 Update table to indicate Harbor can be used with PKS on GCP and AWS
  index.html.md.erb
Labels: unscheduled

#522 Document limitations about backup&restore pks clusters
  backup-and-restore.html.md.erb
  bbr-backup-cluster.html.md.erb
  bbr-restore-cluster.html.md.erb
Labels: unscheduled

#524 MT0 json needs brackets around fip and block ids
  network-profiles-define.html.md.erb
Labels: scheduled

#527 PKS 1.3 accepts * as a no_proxy field
  proxies.html.md.erb
Labels: scheduled

#529 Update table to show support for Harbor for 1.2
  index.html.md.erb
Labels: scheduled

#528 Update table indicating support for Harbor
  index.html.md.erb
Labels: scheduled

#530 Adding FIP clarification if multiple for 1.2
  network-profiles-define.html.md.erb
Labels: scheduled

#532 Add clarfication about 2 FIP IDs for 1.4
  network-profiles-define.html.md.erb
Labels: in progress

#534 Adding note to PKS installation with NSX-T about mutual exclusivity o…
  installing-nsx-t.html.md.erb
Labels: in progress

#535 Adding vSphere 6.7 u1 for PKS 1.3
  vsphere-nsxt-requirements.html.md.erb
  vsphere-requirements.html.md.erb
Labels: unscheduled

#538 Adding note about MPD
  vsphere-nsxt-rpd-mpd.html.md.erb
Labels: in progress
